export const APP_CONFIG = {
  name: 'TracePoint',
  version: '1.0.0',
  description: 'Missing Person Reporting & Tracking System',
  apiBaseUrl: import.meta.env.VITE_API_URL || 'http://localhost:5000/api',
  mapTileUrl: import.meta.env.VITE_MAP_TILE_URL || 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
  mapAttribution: import.meta.env.VITE_MAP_ATTRIBUTION || '&copy; OpenStreetMap contributors',
}

export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  VERIFY_OTP: '/verify-otp',
  DASHBOARD: '/dashboard',
  REPORTS: '/reports',
  REPORT_DETAIL: (id) => `/reports/${id}`,
  REPORT_NEW: '/reports/new',
  MAP_TRACKING: '/map-tracking',
  FACIAL_RECOGNITION: '/facial-recognition',
  MESSAGES: '/messages',
  ALERTS: '/alerts',
  STATISTICS: '/statistics',
  USERS: '/users',
  ORGANIZATIONS: '/organizations',
  CASE_MANAGEMENT: '/case-management',
  REPORTS_ANALYTICS: '/reports-analytics',
  SETTINGS: '/settings',
}
